# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/PC_Generate.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/PC_Add4.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/PC4_Jump.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/PC4_AddOffset.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/Multiplexer4.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/Register_IR.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/Register.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/RegFile.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/PC.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/Multiplexer3.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/Multiplexer2.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/InsMem.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/DataMem.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/ALU.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/WB.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/Mem.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/IF.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/ID.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/Exe.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/EliminationBuffet.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/Display.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/DataExtend.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/ControlUnit.v
  D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/sources_1/new/Multicycle_CPU.v
}
read_xdc D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/constrs_1/new/Multicycle_CPU_Constrs.xdc
set_property used_in_implementation false [get_files D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.srcs/constrs_1/new/Multicycle_CPU_Constrs.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup/Multicycle_CPU.cache/wt [current_project]
set_property parent.project_dir D:/Vivado_projects/Multicycle_CPU_Basys3_Bakeup [current_project]
catch { write_hwdef -file Multicycle_CPU.hwdef }
synth_design -top Multicycle_CPU -part xc7a35tcpg236-1
write_checkpoint Multicycle_CPU.dcp
report_utilization -file Multicycle_CPU_utilization_synth.rpt -pb Multicycle_CPU_utilization_synth.pb
