# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/StateModule.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/TempReg.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/RegFile.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/PC.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/IRAM.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/FourToOne.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/Extend.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/DRAM.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/ControlUnit.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/ALU.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/RMV_BJ.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/MCPU.v
  E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/sources_1/imports/new/ShowMCPU.v
}
read_xdc E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/constrs_1/new/SCPU.xdc
set_property used_in_implementation false [get_files E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.srcs/constrs_1/new/SCPU.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/DigitalFundamentals/vivado/ShowMCPU/ShowMCPU.cache/wt [current_project]
set_property parent.project_dir E:/DigitalFundamentals/vivado/ShowMCPU [current_project]
catch { write_hwdef -file ShowMCPU.hwdef }
synth_design -top ShowMCPU -part xc7a35tcpg236-1
write_checkpoint ShowMCPU.dcp
report_utilization -file ShowMCPU_utilization_synth.rpt -pb ShowMCPU_utilization_synth.pb
