# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/RegFile.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/rd_rt.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/RAM.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/PC_Join.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/PCAddOffset.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/PCAdd4.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/PC.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/Multiplexer4.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/IR.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/DBDataSrcSelect.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/DataExtend.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/ControlUnit.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/ALUSrcBSelect.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/ALUSrcASelect.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/ALU.v
  D:/Vivado_projects/Single_CPU/Single_CPU.srcs/sources_1/new/Single_CPU.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado_projects/Single_CPU/Single_CPU.cache/wt [current_project]
set_property parent.project_dir D:/Vivado_projects/Single_CPU [current_project]
catch { write_hwdef -file Single_CPU.hwdef }
synth_design -top Single_CPU -part xc7a35tcpg236-1
write_checkpoint Single_CPU.dcp
report_utilization -file Single_CPU_utilization_synth.rpt -pb Single_CPU_utilization_synth.pb
